<h3>Créer un compte</h3>
<?php if(isset($error)):?>
	<p class="error">
		<?= $error; ?>
	</p>
<?php endif;?>
<form action="index.php?p=signup" method="POST">
	<nav>
		<ul>
			<li>
				<label for="email" id="email">Email</label>
				<br>
				<input type="email" name="email" id="email" value="<?=$email;?>"/>
			</li>
			<br>
			<li>
				<label for="password" id="password">Mot de passe</label>
				<br>
				<input type="text" name="password" id="password"/>
			</li>
			<br>
			<li>
				<label for="firstname" id="firstname">Prénom</label>
				<br>
				<input type="text" name="firstname" id="firstname" value="<?=$firstname;?>"/>
			</li>
			<br>
			<li>
				<label for="lastname" id="lastname">Nom</label>
				<br>
				<input type="text" name="lastname" id="lastname" value="<?=$lastname;?>"/>
			</li>
			<br>
			<li>
				<label for="birthdate" id="birthdate">Date de naissance</label>
				<br>
				<input type="date" name="birthdate" id="birthdate" value="<?=$birthdate;?>"/>
			</li>
			<br>
			<li>
				<label for="adress" id="adress">Adresse</label>
				<br>
				<input type="text" name="adress" id="adress" value="<?=$adress;?>"/>
			</li>
			<br>
			<li>
				<label for="zipcode" id="zipcode">Code postal</label>
				<br>
				<input type="text" name="zipcode" id="zipcode" value="<?=$zipcode;?>"/>
			</li>
			<br>
			<li>
				<label for="city" id="city">Ville</label>
				<br>
				<input type="city" name="city" id="city" value="<?=$city;?>"/>
			</li>
			<br>
			<li>
				<label for="gender" id="gender">Sexe</label>
				<br>
				<input type="radio" name="gender" id="gender" value="M" <?php if($gender=='M'){echo'checked';}?>/>
				<label for="male" id="male">Homme</label>
				<input type="radio" name="gender" id="female" value="F" <?php if($gender=='F'){echo'checked';}?>/>
				<label>Femme</label>
			</li>
			<br>
			<li>
				<input type="submit" id="submit" value="Envoyer" />
			</li>
		</ul>
	</nav>
</form>

<br>

<nav>
    <ul>
        <li>
            <article>
                <a id="retour" href="index.php">Retour vers l'accueil</a>
            </article>
        </li>
    </ul>
</nav>